# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo Task' do
pod 'AFNetworking'
pod 'objectiveflickr'


  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo Task

  target 'Demo TaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo TaskUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
